version: "3.8"

services:
  backend:
    build: ./backend
    container_name: battlecard-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - vector-db
    volumes:
      - ./backend/src:/app/src

  frontend:
    build: ./frontend
    container_name: battlecard-frontend
    ports:
      - "8080:80"

  vector-db:
    image: milvusdb/milvus:2.2.9
    container_name: vector-db
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus

volumes:
  milvus_data: 